<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.22621.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <PublishTrimmed>false</PublishTrimmed>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <StartupObject>FI2319Native.Program</StartupObject>
    <AssemblyName>FI2319 Clinic Scale</AssemblyName>
    <RootNamespace>FI2319Native</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Page Remove="MainWindow.xaml" />
    <EmbeddedResource Include="MainWindow.xaml" LogicalName="MainWindow.xaml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Diahon.WinUI.Printing.Wpf" Version="0.2.0-alpha" />
  </ItemGroup>
</Project>
